import type { Metadata } from "next";
import { Cormorant_Garamond, Overpass } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  display: "swap",
  variable: "--font-cormorant-garamond",
  weight: ["400", "600"],
  subsets: ["latin"],
});

const overpass = Overpass({
  display: "swap",
  variable: "--font-overpass",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${overpass.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
